"""initial migration

Revision ID: 114aee2ddff4
Revises: None
Create Date: 2016-05-09 20:37:48.513756

"""

# revision identifiers, used by Alembic.
revision = '114aee2ddff4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icao')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.Column('seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], [u'aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('vertical_rate', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], [u'flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_position')
    op.drop_table('flight')
    op.drop_table('aircraft')
    ### end Alembic commands ###
